const Images = {
  mainHeading: "/assets/icons/mainIcon.png",
  searchIcon: "/assets/icons/search.svg",
  notifyIcon: "/assets/icons/notify.svg",
  logOutIcon: "/assets/icons/exit.png",
  threeLine: "/assets/icons/threeLines.png",
  emailIcon: "/assets/icons/email.svg",
  dashIcon: "/assets/icons/dashboard.svg",
  calenderIcon: "/assets/icons/calender.svg",
  analyticsIcon: "/assets/icons/anali.svg",
  taskIcon: "/assets/icons/bx_task.svg",
  patientIcon: "/assets/icons/patient.svg",
  settingIcon: "/assets/icons/setting.svg",
  helpIcon: "/assets/icons/help.svg",
  threeDotIcon: "/assets/icons/threeDot.svg",
  loginImage: "/assets/image/Patients.png",
  pluseIcon: "/assets/icons/pluse.png",
  pluseBlackIcon: "/assets/icons/blackPluse.svg",
  filterIcon: "/assets/icons/filter.svg",
  clarityIcon: "/assets/icons/clarity.svg",
  blueUser: "/assets/icons/blueUser.svg",
  clockTime: "/assets/icons/carbonTime.svg",
  fluentLocation: "/assets/icons/fluentLocation.svg",
  googleIcon: "/assets/icons/google-icon.svg",
  blackDot: "/assets/icons/blackDot.svg",
  dorpDown: "assets/icons/dropDown.svg",
  delete: "/assets/icons/delete.svg",
  edit: "/assets/icons/edit.svg",
  increase: "/assets/icons/increase.svg",
  decrease: "/assets/icons/decrease .svg",
};

export default Images;
